import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Authprovider from "./context/Authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex justify-center items-start p-6 min-h-screen">
        <Authprovider>{children}</Authprovider>
      </body>
    </html>
  );
}
